### PR TITLE
Update dataportal-public.rst

### PR DESCRIPTION
**Pull request by Sudeepa14**
Updated the correct installation guideline for daf-dataportal-backend.

### CODE REVIEW

**Comment by giux78** [comment]
Sorry, but this is a front-end application not backend

**Comment by Sudeepa14** [comment]
My bad I have update 
**daf-docs/dataportal/dataportal-public.rst**   instead of updating 
**daf-docs/installation/dataportal/dataportal-public.rst**  🤕 
[This ](http://daf-docs.readthedocs.io/en/latest/installation/dataportal/dataportal-public.html)should be updated, shouldn't it?

**Comment by giux78** [comment]
No. It is still a node application isn't it?

**Comment by Sudeepa14** [comment]
😟 😧 Can't see anything related to Node. Not even a package.json. [This ](https://github.com/italia/daf-dataportal-backend)is the repo that the [doc ](http://daf-docs.readthedocs.io/en/latest/installation/dataportal/dataportal-public.html) is pointing.
image
                                                                                                                 ↓↓↓↓↓↓
image

Have I missed something out?

**Pull request closed without merging**
